In [2]:
import numpy as np
a = np.arange(11, 36).reshape(5, 5)
print(a,'\n')

red    = a[0, 1:4] 
blue   = a[:, 1::2]  
green  = a[:3,2] 
purple = a[0:3:2,4]   
yellow = a[0,0]

print('red:',red,'\nblue:',blue,'\ngreen:\n',green,'\npurple:',purple, '\nyellow',yellow)


[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]] 

red: [12 13 14] 
blue: [[12 14]
 [17 19]
 [22 24]
 [27 29]
 [32 34]] 
green:
 [13 18 23] 
purple: [15 25] 
yellow 11


## Class exercise 2: cube
1. Slice out [12 13 14] from the above cube using only one slice. e.g: a[:,:,:]
2. Slice out [3 12 21].
3. Slice out all y-values where x is 2 and z is 0.

In [3]:
a = np.arange(0, 27).reshape((3, 3, 3))# = (z, y, x)
print(a[1,1,:])
print(a[:,1,0])
print(a[0,:,2])

[12 13 14]
[ 3 12 21]
[2 5 8]


### Class exercise: masking
- For the dataset: `data = np.arange(1,101).reshape(10,10)`
  - apply a mask that will return only the even numbers
  - using `np.where()` return only numbers that ends with 6


In [4]:
data = np.arange(1,101).reshape(10,10)
a = data[data%2 ==0]
b =  np.where(data % 10 ==6)
print('Even numbers: ',a)
print('Numbers that end with 6: ',data[b])

Even numbers:  [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
Numbers that end with 6:  [ 6 16 26 36 46 56 66 76 86 96]


## Exercise numpy and csv

1. load the csv file: befkbhalderstatkode.csv into a numpy ndarray
2. How many german children of 0 years were there in Copenhagen in 2015?
3. create a function that can take any combination of the 4 parameters:AAR,BYDEL,ALDER,STATKODE and return population data
4. create a new function like previous so that it can sum values for all ages if age is not provided to the function
5. further add functionality to sum values if citizenship or area was not provided to function.
6. create a new function that can also give average values for each year if year whas not provided.
7. create a function, that given year and nationality can return which area had the most of these nationals by that year. Test it by finding out which area had the most Moroccan people in both 1992 and 2015
8. Find the Area(s) where fewest foreingers lived in Copenhagen in 1992 and 2015 respectively
9. Find out what age most French people have in 2015

In [5]:
filename = '../data/befkbhalderstatkode.csv'
data = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
dd = data


In [6]:
mask = (dd[:,0] == 2015) & (dd[:,2] == 0) & (dd[:,3] == 5180)
print('German children aged 0 in cph in 2015\n',np.sum(dd[mask][:,4]))

German children aged 0 in cph in 2015
 35


In [19]:
def population_data(year, area=None, age=None , country=None):
    filename = '../data/befkbhalderstatkode.csv'
    dd = np.genfromtxt(filename, delimiter=',', dtype=np.uint, skip_header=1)
    mask_year = dd[:, 0] == year 
    mask_area = dd[:, 1] == area if area else True
    mask_age = dd[:, 2] == age if age else True
    mask_country = dd[:, 3] == country if country else True
    population = (dd[(mask_year) & (mask_area)  & (mask_age)  & (mask_country)])
    return population[:,4].sum()



In [17]:
print('Population of 37 year olds in valby 2015:',population_data(2014,5,37,5100))


Population of 37 year olds in valby 2015: 775


In [20]:
print('Population in valby 2015:',population_data(2014,5,None,5100))

Population in valby 2015: 44438


6. create a new function that can also give average values for each year if year whas not provided.

In [33]:
def average_population(year =None):
    age = 0
    mask_year = dd[:,0] == year if year else True
    data = dd[mask_year]
    
    for el in data:
        age += el[2].sum() * el[4].sum()
        
    return age / data[:,4].sum()

year = 2015
print('Average age of population in',year,average_population(year))

Average age of population in 2015 35.38101655192617
